import type { Metadata } from 'next'
import 'tailwind-config/styles.css'

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout(props: RootLayoutProps) {
  const { children } = props

  return (
    <html data-color-scheme="dark" lang="en">
      <body>{children}</body>
    </html>
  )
}
